# Cloudflare Pages Configuration
name = "designstudio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:optimize"
publish = "dist"

[build.environment_variables]
NODE_ENV = "production"
CUSTOM_DOMAIN = "designstudio.pages.dev"

[[build.environment_variables]]
GA_TRACKING_ID = "GA-XXXXXXXXX-X"

[env.production]
name = "designstudio-production"

[env.production.vars]
ENVIRONMENT = "production"
CUSTOM_DOMAIN = "designstudio.com"

[env.staging]
name = "designstudio-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
CUSTOM_DOMAIN = "staging.designstudio.pages.dev"

# Custom domains
[[env.production.routes]]
pattern = "designstudio.com"
custom_domain = true

[[env.production.routes]]
pattern = "www.designstudio.com"
custom_domain = true

# Security settings
[security]
level = "high"

# Performance settings
[performance]
minify = true
compression = "gzip"